name: Release Chemotion CLI

on:
  push:
    tags:
      - "*"

jobs:
  build-release-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Build Go for all OSes
        run: |
          cp   payload/docker-compose.yml .
          cp   payload/backup.sh .
          go   mod        verify
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          CGO_ENABLED=0   GOOS=linux    GOARCH=amd64  go  build -ldflags "-X cli.versionCLI=${{ env.VERSION }}" -o chemCLI
          CGO_ENABLED=0   GOOS=darwin   GOARCH=arm64  go  build -ldflags "-X cli.versionCLI=${{ env.VERSION }}" -o chemCLI.arm.osx
          CGO_ENABLED=0   GOOS=darwin   GOARCH=amd64  go  build -ldflags "-X cli.versionCLI=${{ env.VERSION }}" -o chemCLI.amd.osx
          CGO_ENABLED=0   GOOS=windows  GOARCH=amd64  go  build -ldflags "-X cli.versionCLI=${{ env.VERSION }}" -o chemCLI.exe
      - name: Release Binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            chemCLI
            chemCLI.arm.osx
            chemCLI.amd.osx
            chemCLI.exe
            docker-compose.yml
            backup.sh
          token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
