name: Release Chemotion CLI

on:
  push:
    tags:
      - "*"

jobs:
  build-release-binary:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Build Go for all OSes
        run: |
          cp   payload/docker-compose.yml .
          cp   payload/backup.sh .
          go   mod                        verify
          GOOS=linux    GOARCH=amd64  go  build -o chemCLI
          GOOS=darwin   GOARCH=arm64  go  build -o chemCLI.arm.osx
          GOOS=darwin   GOARCH=amd64  go  build -o chemCLI.amd.osx
          GOOS=windows  GOARCH=amd64  go  build -o chemCLI.exe
      - name: Release Binaries
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            chemCLI
            chemCLI.arm.osx
            chemCLI.amd.osx
            chemCLI.exe
            docker-compose.yml
            backup.sh
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
